from __future__ import annotations

from sqlalchemy.orm import Session

from app.models.media_asset import (
    MediaAsset,
)

from app.services.media_asset_service import (
    MediaAssetService,
)


class VisualService:
    """
    N1MOX30 Visual Service.

    This service is the bridge between:

    AI Visual Providers
        ↓
    VisualService
        ↓
    MediaAssetService
        ↓
    Video Timeline Engine

    Future providers can generate:

    - scene images
    - B-roll videos
    - animated visuals
    - AI-generated video clips
    - overlays
    - thumbnails
    """

    def __init__(
        self,
        db: Session,
    ) -> None:
        self.db = db

        self.media_asset_service = (
            MediaAssetService(
                db,
            )
        )

    def register_scene_image(
        self,
        *,
        user_id: str,
        project_id: str | None,
        content_id: str | None,
        scene_number: int,
        name: str,
        provider_name: str,
        provider_asset_id: str | None = None,
        public_url: str | None = None,
        width: int | None = None,
        height: int | None = None,
        metadata: dict | None = None,
    ) -> MediaAsset:
        """
        Register an image generated by
        a visual provider.
        """

        return (
            self.media_asset_service
            .create_asset(
                user_id=user_id,
                project_id=project_id,
                content_id=content_id,
                asset_type="image",
                media_type="image",
                name=name,
                description=(
                    f"Scene {scene_number} image"
                ),
                original_filename=None,
                storage_provider=provider_name,
                storage_path=None,
                public_url=public_url,
                provider_asset_id=provider_asset_id,
                mime_type="image/*",
                file_extension=None,
                file_size_bytes=None,
                width=width,
                height=height,
                duration_seconds=None,
                frame_rate=None,
                scene_number=scene_number,
                asset_role="scene_visual",
                metadata=metadata,
                max_retries=3,
            )
        )

    def register_scene_video(
        self,
        *,
        user_id: str,
        project_id: str | None,
        content_id: str | None,
        scene_number: int,
        name: str,
        provider_name: str,
        provider_asset_id: str | None = None,
        public_url: str | None = None,
        width: int | None = None,
        height: int | None = None,
        duration_seconds: float | None = None,
        frame_rate: float | None = None,
        metadata: dict | None = None,
    ) -> MediaAsset:
        """
        Register a video generated by
        a visual provider.
        """

        return (
            self.media_asset_service
            .create_asset(
                user_id=user_id,
                project_id=project_id,
                content_id=content_id,
                asset_type="video",
                media_type="video",
                name=name,
                description=(
                    f"Scene {scene_number} video"
                ),
                original_filename=None,
                storage_provider=provider_name,
                storage_path=None,
                public_url=public_url,
                provider_asset_id=provider_asset_id,
                mime_type="video/*",
                file_extension=None,
                file_size_bytes=None,
                width=width,
                height=height,
                duration_seconds=duration_seconds,
                frame_rate=frame_rate,
                scene_number=scene_number,
                asset_role="scene_visual",
                metadata=metadata,
                max_retries=3,
            )
        )

    def mark_visual_ready(
        self,
        *,
        asset: MediaAsset,
    ) -> MediaAsset:
        """
        Mark a visual asset ready.
        """

        return (
            self.media_asset_service
            .update_asset_status(
                asset=asset,
                status="ready",
            )
        )

    def mark_visual_failed(
        self,
        *,
        asset: MediaAsset,
        error_message: str,
    ) -> MediaAsset:
        """
        Mark a visual generation as failed.
        """

        return (
            self.media_asset_service
            .update_asset_status(
                asset=asset,
                status="failed",
                error_message=error_message,
            )
        )